CREATE TABLE SPECTACLE
(
    ID_SPECTACLE INT NOT NULL PRIMARY KEY AUTO_INCREMENT ,
    DATE_SPECTACLE DATE NOT NULL ,
    HORAIRE_SPECTACLE CHAR(20) NOT NULL ,
    DUREE_SPECTACLE INT NOT NULL ,
    TARIF_SPECTACLE DOUBLE NOT NULL ,
    EXTRAIT_SPECTACLE CHAR(100) NOT NULL ,
    TITRE_SPECTACLE CHAR(100) NOT NULL ,
    DESCRIPTION_SPECTACLE CHAR(200) NOT NULL ,
    IMAGE_SPECTACLE CHAR(200) NOT NULL ,
    STYLE_MUSIQUE CHAR(100) NOT NULL
);


CREATE TABLE LIEU
(
    ID_LIEU INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    NOM_LIEU CHAR(100) NOT NULL ,
    ADRESSE_LIEU CHAR(200) NOT NULL ,
    Nb_Places_Debout INT NOT NULL ,
    Nb_Places_Assises INT NOT NULL ,
    IMAGE_LIEU CHAR(255) NOT NULL
);


CREATE TABLE SOIREE
(
    ID_SOIREE INT NOT NULL PRIMARY KEY AUTO_INCREMENT ,
    NOM_SOIREE CHAR(100) NOT NULL ,
    DATE_SOIREE DATE NOT NULL ,
    THEMATIQUE CHAR(100) NOT NULL ,
    HORAIRE_DEBUT CHAR(100) NOT NULL ,
    ID_LIEU INT NOT NULL 	
);


CREATE TABLE ARTISTE
(
    ID_ARTISTE INT NOT NULL PRIMARY KEY AUTO_INCREMENT ,
    NOM_ARTISTE CHAR(100) NOT NULL
);


CREATE TABLE UTILISATEUR
(
    ID_UTILISATEUR INT NOT NULL PRIMARY KEY AUTO_INCREMENT ,
    NOM_UTILISATEUR CHAR(100) NOT NULL ,
    EMAIL_UTILISATEUR CHAR(100) NOT NULL ,
    TELEPHONE_UTILISATEUR CHAR(20) ,
    DROIT_UTILISATEUR INT NOT NULL ,
    PASSWORD_UTILISATEUR CHAR(100) NOT NULL	
);
ALTER TABLE SOIREE
ADD CONSTRAINT CCKLP FOREIGN KEY(ID_LIEU) REFERENCES LIEU(ID_LIEU);
CREATE TABLE SOIREE_SPECTACLE
(
    ID_SOIREE INT NOT NULL ,
    ID_SPECTACLE INT NOT NULL
    );
CREATE TABLE ARTISTE_SPECTACLE
(
    ID_ARTISTE INT NOT NULL ,
    ID_SPECTACLE INT NOT NULL 
);


CREATE TABLE UTILISATEUR_SOIREE
(
    ID_UTILISATEUR INT NOT NULL ,
    ID_SOIREE INT NOT NULL
);


CREATE TABLE UTILISATEUR_SPECTACLE
(
	ID_UTILISATEUR INT NOT NULL ,
	ID_SPECTACLE INT NOT NULL
);


ALTER TABLE UTILISATEUR_SPECTACLE
	ADD CONSTRAINT CPKUS PRIMARY KEY(ID_UTILISATEUR, ID_SPECTACLE);


ALTER TABLE UTILISATEUR_SOIREE
    ADD CONSTRAINT CPKUS1 PRIMARY KEY(ID_UTILISATEUR,ID_SOIREE);


ALTER TABLE ARTISTE_SPECTACLE
    ADD CONSTRAINT CPKUS2 PRIMARY KEY(ID_ARTISTE,ID_SPECTACLE);
   
ALTER TABLE UTILISATEUR_SPECTACLE
  ADD CONSTRAINT CCKUS FOREIGN KEY(ID_UTILISATEUR) REFERENCES UTILISATEUR(ID_UTILISATEUR);


ALTER TABLE UTILISATEUR_SPECTACLE
  ADD CONSTRAINT CCKUS2 FOREIGN KEY(ID_SPECTACLE) REFERENCES SPECTACLE(ID_SPECTACLE);


ALTER TABLE ARTISTE_SPECTACLE
  ADD CONSTRAINT CCKLL FOREIGN KEY(ID_SPECTACLE) REFERENCES SPECTACLE(ID_SPECTACLE);


ALTER TABLE ARTISTE_SPECTACLE
  ADD CONSTRAINT CCKLM FOREIGN KEY(ID_ARTISTE) REFERENCES ARTISTE(ID_ARTISTE);


ALTER TABLE UTILISATEUR_SOIREE
  ADD CONSTRAINT CCKLC FOREIGN KEY(ID_UTILISATEUR) REFERENCES UTILISATEUR(ID_UTILISATEUR);


ALTER TABLE UTILISATEUR_SOIREE
  ADD CONSTRAINT CCKLV FOREIGN KEY(ID_SOIREE) REFERENCES SOIREE(ID_SOIREE);


ALTER TABLE SOIREE_SPECTACLE
    ADD CONSTRAINT CPKSP PRIMARY KEY(ID_SOIREE,ID_SPECTACLE);
ALTER TABLE SOIREE_SPECTACLE
  ADD CONSTRAINT CCKLA FOREIGN KEY(ID_SPECTACLE) REFERENCES SPECTACLE(ID_SPECTACLE);


ALTER TABLE SOIREE_SPECTACLE
  ADD CONSTRAINT CCKLZ FOREIGN KEY(ID_SOIREE) REFERENCES SOIREE(ID_SOIREE);




INSERT INTO SPECTACLE(ID_SPECTACLE,DATE_SPECTACLE,HORAIRE_SPECTACLE,DUREE_SPECTACLE,TARIF_SPECTACLE,EXTRAIT_SPECTACLE,TITRE_SPECTACLE,DESCRIPTION_SPECTACLE,IMAGE_SPECTACLE,STYLE_MUSIQUE)
VALUES
  (1,'2024-11-10',"19h30",30,15,"https://www.youtube.com/embed/9mpbBL2XUwg?si=UrjXESmOuZ-qsF20","Linkin Park de retour !","Suite à la reformation du groupe, ces derniers viendront faire une performace de leur nouvel album","https://static.posters.cz/image/750/affiches-et-posters/linkin-park-plan-b-i3292.jpg","Rock/Nu-Métal"),
  (2,'2024-11-14',"19h00",45,20,"https://www.youtube.com/embed/kLCs1K6vWbA?si=r8gtSWDlkaijOJ0j","Radical optimism","Dua Lipa, l'artiste tendance du moment nous fait le plaisir de sa venue au festival","https://media.vogue.fr/photos/66e3d8d4ac26cc8b4fedeb09/master/w_1600%2Cc_limit/DUALIPA_NEWDATES_1080x1350%255B1%255D.jpg","Pop"),
  (3,'2024-11-18',"20h30",25,13,"https://www.youtube.com/embed/Oz2Qmrhc004?si=EN1-A_NZRhdLh0bc","V","Une performance de l'un des rappeurs français le plus reconnu aujourd'hui","https://www.mokaddict.com/media/cache/event_detail_main_picture/2019/11/8041-banner-1125.jpg","Rap"),
  (4,'2024-11-16',"19h00",35,16,"https://www.youtube.com/embed/yGDcxgauGwM?si=CQdeQqvgDAAfp5Fs","Moliere, le spectacle musical","Une reprise des classiques de Molière","https://agendaculturel.emstorage.fr/le-voyage-de-moliere-bji-36249118.jpg","Classique"),
  (5,'2024-11-17',"19h30",20,10,"https://www.youtube.com/embed/P5NkTMsgpkk?si=XT2dkxP8uBynZDdv","Le lac des Cygnes","Un spectacle de danse classique sur le lac des cygnes","https://arenaloiretrelaze.fr/wp-content/uploads/2019/05/le-lac-des-cygnes-visuel.jpg","danse classique");


INSERT INTO LIEU(ID_LIEU,NOM_LIEU,ADRESSE_LIEU,Nb_Places_Debout,Nb_Places_Assises,IMAGE_LIEU)
VALUES
  (1,"Parc Expo de Vandœuvre-lès-Nancy","Rue Catherine Opalinska, 54500 Vandœuvre-lès-Nancy",100,1000,"https://destination-nancy.com/wp-content/uploads/2024/10/Foire-Expo-2024_ambiance_50-scaled.jpg"),
  (2,"Zénith de Nancy","Rue du Zénith, 54320 Maxéville",0,4710,"https://groupe-s-pass.com/tse/wp-content/uploads/2018/11/Nancy-salle-assis-1.jpg"),
  (3,"Palais des sports Jean Weille de Gentilly","12 Rue du Capitaine Guynemer, 54100 Nancy",0,6043,"https://th.bing.com/th/id/OLC.j3Ddt4mFR04hzg480x360?rs=1&pid=ImgDetMain");


INSERT INTO SOIREE(ID_SOIREE,NOM_SOIREE,DATE_SOIREE,THEMATIQUE,HORAIRE_DEBUT,ID_LIEU)
VALUES
  (1,"Retour de légendes",'2024-11-10',"Rétro","19h30",1),
  (2,"Tendances",'2024-11-14',"Tendances","19h00",2),
  (3,"Artistes français",'2024-11-18',"Artistes français","20h30",3);


INSERT INTO ARTISTE(ID_ARTISTE,NOM_ARTISTE)
VALUES
  (1,"Linkin Park"),
  (2,"Dua Lipa"),
  (3,"Vald");




INSERT INTO UTILISATEUR (ID_UTILISATEUR,NOM_UTILISATEUR,EMAIL_UTILISATEUR,TELEPHONE_UTILISATEUR,DROIT_UTILISATEUR,PASSWORD_UTILISATEUR)
VALUES
  (1,"Keith Reyes","ipsum@outlook.net","03 48 83 63 28",1,"$2y$10$gbL9CEIjXukRgrEtQhUpAu9tkQQS6UJjx12LygFTrnxqCvZNK2J8W"),
  (2,"Rigel Long","mattis.velit@icloud.com","03 46 45 79 14",15,"$2y$10$N0D/lGWY8Vh/jLBS7rUSg.Lah.BAzWxFmk3L9ryfnfsj/x8Zm4Er."),
  (3,"Nolan Gardner","volutpat.nulla@outlook.net","02 22 87 39 28",50,"$2y$10$D7pHs2C7DnnysuYpEPaZJeGu/v86q0sU92TOEK.R9wdBVVh1tp9Bm");
INSERT INTO ARTISTE_SPECTACLE (ID_ARTISTE,ID_SPECTACLE)
VALUES
  (1,1),
  (2,2),
  (3,3),
  (2,4),
  (3,5);


INSERT INTO SOIREE_SPECTACLE(ID_SOIREE,ID_SPECTACLE)
VALUES
  (1,1),
  (2,2),
  (3,3),
  (1,4),
  (2,5);


INSERT INTO UTILISATEUR_SOIREE(ID_UTILISATEUR,ID_SOIREE)
VALUES
  (1,1),
  (2,2),
  (3,3);